<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
    } 

    /*
     * Listing of empresas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('empresa/index?');
        $config['total_rows'] = $this->Empresa_model->get_all_empresas_count();
        $this->pagination->initialize($config);

        $data['empresas'] = $this->Empresa_model->get_all_empresas($params);
        
        $data['_view'] = 'empresa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new empresa
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('cnpj','Cnpj','required|max_length[25]');
		$this->form_validation->set_rules('senha','Senha','required|max_length[250]');
		$this->form_validation->set_rules('email','Email','max_length[60]');
		$this->form_validation->set_rules('telefone','Telefone','max_length[14]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'cnpj' => $this->input->post('cnpj'),
				'senha' => $this->input->post('senha'),
				'email' => $this->input->post('email'),
				'telefone' => $this->input->post('telefone'),
            );
            
            $empresa_id = $this->Empresa_model->add_empresa($params);
            redirect('empresa/index');
        }
        else
        {            
            $data['_view'] = 'empresa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a empresa
     */
    function edit($id)
    {   
        // check if the empresa exists before trying to edit it
        $data['empresa'] = $this->Empresa_model->get_empresa($id);
        
        if(isset($data['empresa']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('cnpj','Cnpj','required|max_length[25]');
			$this->form_validation->set_rules('senha','Senha','required|max_length[250]');
			$this->form_validation->set_rules('email','Email','max_length[60]');
			$this->form_validation->set_rules('telefone','Telefone','max_length[14]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'cnpj' => $this->input->post('cnpj'),
					'senha' => $this->input->post('senha'),
					'email' => $this->input->post('email'),
					'telefone' => $this->input->post('telefone'),
                );

                $this->Empresa_model->update_empresa($id,$params);            
                redirect('empresa/index');
            }
            else
            {
                $data['_view'] = 'empresa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The empresa you are trying to edit does not exist.');
    } 

    /*
     * Deleting empresa
     */
    function remove($id)
    {
        $empresa = $this->Empresa_model->get_empresa($id);

        // check if the empresa exists before trying to delete it
        if(isset($empresa['id']))
        {
            $this->Empresa_model->delete_empresa($id);
            redirect('empresa/index');
        }
        else
            show_error('The empresa you are trying to delete does not exist.');
    }
    
}
