<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vagas_has_colaboradore extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vagas_has_colaboradore_model');
    } 

    /*
     * Listing of vagas_has_colaboradores
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('vagas_has_colaboradore/index?');
        $config['total_rows'] = $this->Vagas_has_colaboradore_model->get_all_vagas_has_colaboradores_count();
        $this->pagination->initialize($config);

        $data['vagas_has_colaboradores'] = $this->Vagas_has_colaboradore_model->get_all_vagas_has_colaboradores($params);
        
        $data['_view'] = 'vagas_has_colaboradore/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vagas_has_colaboradore
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $vagas_has_colaboradore_id = $this->Vagas_has_colaboradore_model->add_vagas_has_colaboradore($params);
            redirect('vagas_has_colaboradore/index');
        }
        else
        {            
            $data['_view'] = 'vagas_has_colaboradore/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a vagas_has_colaboradore
     */
    function edit($vagas_id)
    {   
        // check if the vagas_has_colaboradore exists before trying to edit it
        $data['vagas_has_colaboradore'] = $this->Vagas_has_colaboradore_model->get_vagas_has_colaboradore($vagas_id);
        
        if(isset($data['vagas_has_colaboradore']['vagas_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Vagas_has_colaboradore_model->update_vagas_has_colaboradore($vagas_id,$params);            
                redirect('vagas_has_colaboradore/index');
            }
            else
            {
                $data['_view'] = 'vagas_has_colaboradore/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vagas_has_colaboradore you are trying to edit does not exist.');
    } 

    /*
     * Deleting vagas_has_colaboradore
     */
    function remove($vagas_id)
    {
        $vagas_has_colaboradore = $this->Vagas_has_colaboradore_model->get_vagas_has_colaboradore($vagas_id);

        // check if the vagas_has_colaboradore exists before trying to delete it
        if(isset($vagas_has_colaboradore['vagas_id']))
        {
            $this->Vagas_has_colaboradore_model->delete_vagas_has_colaboradore($vagas_id);
            redirect('vagas_has_colaboradore/index');
        }
        else
            show_error('The vagas_has_colaboradore you are trying to delete does not exist.');
    }
    
}
