<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Colaboradore_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get colaboradore by id
     */
    function get_colaboradore($id)
    {
        return $this->db->get_where('colaboradores',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all colaboradores count
     */
    function get_all_colaboradores_count()
    {
        $this->db->from('colaboradores');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all colaboradores
     */
    function get_all_colaboradores($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('colaboradores')->result_array();
    }
        
    /*
     * function to add new colaboradore
     */
    function add_colaboradore($params)
    {
        $this->db->insert('colaboradores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update colaboradore
     */
    function update_colaboradore($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('colaboradores',$params);
    }
    
    /*
     * function to delete colaboradore
     */
    function delete_colaboradore($id)
    {
        return $this->db->delete('colaboradores',array('id'=>$id));
    }
}
