<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get empresa by id
     */
    function get_empresa($id)
    {
        return $this->db->get_where('empresas',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all empresas count
     */
    function get_all_empresas_count()
    {
        $this->db->from('empresas');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all empresas
     */
    function get_all_empresas($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('empresas')->result_array();
    }
        
    /*
     * function to add new empresa
     */
    function add_empresa($params)
    {
        $this->db->insert('empresas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update empresa
     */
    function update_empresa($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('empresas',$params);
    }
    
    /*
     * function to delete empresa
     */
    function delete_empresa($id)
    {
        return $this->db->delete('empresas',array('id'=>$id));
    }
}
