<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vaga_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vaga by id
     */
    function get_vaga($id)
    {
        return $this->db->get_where('vagas',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all vagas count
     */
    function get_all_vagas_count()
    {
        $this->db->from('vagas');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vagas
     */
    function get_all_vagas($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('vagas')->result_array();
    }
        
    /*
     * function to add new vaga
     */
    function add_vaga($params)
    {
        $this->db->insert('vagas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vaga
     */
    function update_vaga($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vagas',$params);
    }
    
    /*
     * function to delete vaga
     */
    function delete_vaga($id)
    {
        return $this->db->delete('vagas',array('id'=>$id));
    }
}
