<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vagas_has_colaboradore_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vagas_has_colaboradore by vagas_id
     */
    function get_vagas_has_colaboradore($vagas_id)
    {
        return $this->db->get_where('vagas_has_colaboradores',array('vagas_id'=>$vagas_id))->row_array();
    }
    
    /*
     * Get all vagas_has_colaboradores count
     */
    function get_all_vagas_has_colaboradores_count()
    {
        $this->db->from('vagas_has_colaboradores');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vagas_has_colaboradores
     */
    function get_all_vagas_has_colaboradores($params = array())
    {
        $this->db->order_by('vagas_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('vagas_has_colaboradores')->result_array();
    }
        
    /*
     * function to add new vagas_has_colaboradore
     */
    function add_vagas_has_colaboradore($params)
    {
        $this->db->insert('vagas_has_colaboradores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vagas_has_colaboradore
     */
    function update_vagas_has_colaboradore($vagas_id,$params)
    {
        $this->db->where('vagas_id',$vagas_id);
        return $this->db->update('vagas_has_colaboradores',$params);
    }
    
    /*
     * function to delete vagas_has_colaboradore
     */
    function delete_vagas_has_colaboradore($vagas_id)
    {
        return $this->db->delete('vagas_has_colaboradores',array('vagas_id'=>$vagas_id));
    }
}
